### ISSUE TITLE
TrainCardDeck index out of bounds exception

### ISSUE THREAD

**Issue by dSalazar10** [dSalazar10/Ticket_To_Ride#30]
**Describe the bug**
There are only 2 cards in the deck but the loop goes out of bounds:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at model.TrainCardDeck.<init>(TrainCardDeck.java:68)
	at model.Board.<init>(Board.java:31)
	at ticket2ride.Ticket2Ride.main(Ticket2Ride.java:38)

**To Reproduce**
1. Try to compile
2. See error

**Expected behavior**
We should be able to create a new TrainCardDeck:
TrainCardDeck trainDeck = new TrainCardDeck();

@NasarioS

**Comment by dSalazar10** [comment]
My mistake. I needed to merge the updated copy from master.
